"""Add background_jobs table for async task tracking

Revision ID: 13cc72f88bd6
Revises: 7c40b25df1e8
Create Date: 2025-11-30 18:25:13.176062

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '13cc72f88bd6'
down_revision = '7c40b25df1e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('background_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_type', sa.String(length=50), nullable=False),
    sa.Column('celery_task_id', sa.String(length=255), nullable=False),
    sa.Column('parameters', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=True),
    sa.Column('progress_message', sa.String(length=255), nullable=True),
    sa.Column('result', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('background_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_background_jobs_celery_task_id'), ['celery_task_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_background_jobs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_background_jobs_job_type'), ['job_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_background_jobs_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('background_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_background_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_background_jobs_job_type'))
        batch_op.drop_index(batch_op.f('ix_background_jobs_created_at'))
        batch_op.drop_index(batch_op.f('ix_background_jobs_celery_task_id'))

    op.drop_table('background_jobs')
    # ### end Alembic commands ###
