"""Add feedback type tables for issues, photos, and locations

Revision ID: 22c74b1e73f4
Revises: 55400ae3b044
Create Date: 2025-11-04 21:21:54.824611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22c74b1e73f4'
down_revision = '55400ae3b044'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedback_issues',
    sa.Column('feedback_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['feedback_id'], ['feedback.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('feedback_id'),
    sa.CheckConstraint("severity IN ('low', 'medium', 'high') OR severity IS NULL", name='check_severity_values')
    )
    op.create_table('feedback_locations',
    sa.Column('feedback_id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('accuracy', sa.Float(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['feedback_id'], ['feedback.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('feedback_id'),
    sa.CheckConstraint('latitude BETWEEN -90 AND 90', name='check_latitude_range'),
    sa.CheckConstraint('longitude BETWEEN -180 AND 180', name='check_longitude_range'),
    sa.CheckConstraint('accuracy > 0 OR accuracy IS NULL', name='check_accuracy_positive')
    )
    op.create_table('feedback_photos',
    sa.Column('feedback_id', sa.Integer(), nullable=False),
    sa.Column('photo_url', sa.String(length=1024), nullable=True),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['feedback_id'], ['feedback.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('feedback_id')
    )

    # Create indexes for performance
    op.create_index('idx_feedback_issues_feedback_id', 'feedback_issues', ['feedback_id'])
    op.create_index('idx_feedback_photos_feedback_id', 'feedback_photos', ['feedback_id'])
    op.create_index('idx_feedback_locations_feedback_id', 'feedback_locations', ['feedback_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop indexes first
    op.drop_index('idx_feedback_locations_feedback_id', table_name='feedback_locations')
    op.drop_index('idx_feedback_photos_feedback_id', table_name='feedback_photos')
    op.drop_index('idx_feedback_issues_feedback_id', table_name='feedback_issues')

    # Drop tables
    op.drop_table('feedback_photos')
    op.drop_table('feedback_locations')
    op.drop_table('feedback_issues')
    # ### end Alembic commands ###
