"""Add fixed directions feature

Revision ID: 34761a2fc060
Revises: f4e3d2c1b0a9
Create Date: 2026-01-29 20:48:51.687317

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '34761a2fc060'
down_revision = 'f4e3d2c1b0a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('direction_segments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tour_id', sa.UUID(), nullable=False),
    sa.Column('from_site_id', sa.UUID(), nullable=False),
    sa.Column('to_site_id', sa.UUID(), nullable=False),
    sa.Column('segment_order', sa.Integer(), nullable=False),
    sa.Column('direction_text', sa.Text(), nullable=False),
    sa.Column('audio_url', sa.String(length=1024), nullable=True),
    sa.Column('trigger_latitude', sa.Float(), nullable=False),
    sa.Column('trigger_longitude', sa.Float(), nullable=False),
    sa.Column('trigger_radius', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['from_site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tour_id'], ['tours.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('background_jobs', schema=None) as batch_op:
        batch_op.drop_index('ix_background_jobs_celery_task_id')
        batch_op.drop_index('ix_background_jobs_created_at')
        batch_op.drop_index('ix_background_jobs_job_type')
        batch_op.drop_index('ix_background_jobs_status')

    op.drop_table('background_jobs')
    with op.batch_alter_table('tours', schema=None) as batch_op:
        batch_op.add_column(sa.Column('has_fixed_directions', sa.Boolean(), server_default=sa.false(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tours', schema=None) as batch_op:
        batch_op.drop_column('has_fixed_directions')

    op.create_table('background_jobs',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('job_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('celery_task_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('parameters', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('progress', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('progress_message', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('result', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('started_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='background_jobs_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='background_jobs_pkey')
    )
    with op.batch_alter_table('background_jobs', schema=None) as batch_op:
        batch_op.create_index('ix_background_jobs_status', ['status'], unique=False)
        batch_op.create_index('ix_background_jobs_job_type', ['job_type'], unique=False)
        batch_op.create_index('ix_background_jobs_created_at', ['created_at'], unique=False)
        batch_op.create_index('ix_background_jobs_celery_task_id', ['celery_task_id'], unique=False)

    op.drop_table('direction_segments')
    # ### end Alembic commands ###
