"""Add default_music_tracks table

Revision ID: 55400ae3b044
Revises: e7f8g9h0i1j2
Create Date: 2025-11-04 02:22:31.295965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55400ae3b044'
down_revision = 'e7f8g9h0i1j2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('default_music_tracks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('default_music_tracks')
    # ### end Alembic commands ###
