"""Add device_registrations table for device binding

Revision ID: 668d72fddf9a
Revises: d1f2a3b4c5d6
Create Date: 2025-11-01 21:27:37.090675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '668d72fddf9a'
down_revision = 'd1f2a3b4c5d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_registrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.String(length=64), nullable=False),
    sa.Column('device_name', sa.String(length=128), nullable=True),
    sa.Column('platform', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('device_registrations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_device_registrations_device_id'), ['device_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_device_registrations_is_active'), ['is_active'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device_registrations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_device_registrations_is_active'))
        batch_op.drop_index(batch_op.f('ix_device_registrations_device_id'))

    op.drop_table('device_registrations')
    # ### end Alembic commands ###
