"""Add city and neighborhood to sites

Revision ID: 6ca4acaf6756
Revises: a5f1dc324b18
Create Date: 2025-10-23 17:25:50.189353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ca4acaf6756'
down_revision = 'a5f1dc324b18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('city', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('neighborhood', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sites', schema=None) as batch_op:
        batch_op.drop_column('neighborhood')
        batch_op.drop_column('city')

    # ### end Alembic commands ###
