"""Add accuracy and recordedAt to feedback_photos

Revision ID: 7c40b25df1e8
Revises: 9d121067c119
Create Date: 2025-11-07 18:11:38.009440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c40b25df1e8'
down_revision = '9d121067c119'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedback_photos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('accuracy', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('recorded_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedback_photos', schema=None) as batch_op:
        batch_op.drop_column('recorded_at')
        batch_op.drop_column('accuracy')

    # ### end Alembic commands ###
