"""Add ai_traces table for AI prompt logging

Revision ID: 961a9c623460
Revises: b8f2ed456c21
Create Date: 2025-10-27 14:36:35.237741

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '961a9c623460'
down_revision = 'b8f2ed456c21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_traces',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('prompt_name', sa.String(length=100), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('system_prompt', sa.Text(), nullable=True),
    sa.Column('user_prompt', sa.Text(), nullable=False),
    sa.Column('response', sa.Text(), nullable=True),
    sa.Column('raw_request', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('raw_response', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('trace_metadata', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_traces', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_traces_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_traces_prompt_name'), ['prompt_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_traces_provider'), ['provider'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_traces_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_traces', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_traces_status'))
        batch_op.drop_index(batch_op.f('ix_ai_traces_provider'))
        batch_op.drop_index(batch_op.f('ix_ai_traces_prompt_name'))
        batch_op.drop_index(batch_op.f('ix_ai_traces_created_at'))

    op.drop_table('ai_traces')
    # ### end Alembic commands ###
