"""Add latitude and longitude to feedback_photos

Revision ID: 9d121067c119
Revises: 22c74b1e73f4
Create Date: 2025-11-07 18:05:29.013968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d121067c119'
down_revision = '22c74b1e73f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedback_issues', schema=None) as batch_op:
        batch_op.drop_index('idx_feedback_issues_feedback_id')

    with op.batch_alter_table('feedback_locations', schema=None) as batch_op:
        batch_op.drop_index('idx_feedback_locations_feedback_id')

    with op.batch_alter_table('feedback_photos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('latitude', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('longitude', sa.Float(), nullable=True))
        batch_op.drop_index('idx_feedback_photos_feedback_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedback_photos', schema=None) as batch_op:
        batch_op.create_index('idx_feedback_photos_feedback_id', ['feedback_id'], unique=False)
        batch_op.drop_column('longitude')
        batch_op.drop_column('latitude')

    with op.batch_alter_table('feedback_locations', schema=None) as batch_op:
        batch_op.create_index('idx_feedback_locations_feedback_id', ['feedback_id'], unique=False)

    with op.batch_alter_table('feedback_issues', schema=None) as batch_op:
        batch_op.create_index('idx_feedback_issues_feedback_id', ['feedback_id'], unique=False)

    # ### end Alembic commands ###
