"""Remove App Attest fields from device_registrations

Revision ID: a1b516dbc95b
Revises: add_app_attest_fields
Create Date: 2025-11-02 21:28:46.740626

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a1b516dbc95b'
down_revision = 'add_app_attest_fields'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device_registrations', schema=None) as batch_op:
        batch_op.drop_column('app_attest_key_id')
        batch_op.drop_column('attestation_verified')
        batch_op.drop_column('last_assertion_at')
        batch_op.drop_column('attestation_verified_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device_registrations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('attestation_verified_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('last_assertion_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('attestation_verified', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('app_attest_key_id', sa.VARCHAR(length=256), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
